---

## FIXME! or ssl ?
- name: Configure apache
  ansible.builtin.template:
    src: apache2-misp.conf.j2
    dest: "{{ apache_sitedir }}/misp.conf"
    mode: '0644'
    backup: yes
  notify:
    - Restart webserver
    - Restart webserver - docker,debian
    - Restart webserver - docker,redhat

- name: Debian | Disable default apache config
  ansible.builtin.file: dest=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify:
    - Restart webserver
    - Restart webserver - docker,debian
    - Restart webserver - docker,redhat
  when: ansible_os_family == 'Debian'

- name: Debian | ensure required modules are present
  community.general.apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - headers
    - rewrite
  notify:
    - Restart webserver
    - Restart webserver - docker,debian
    - Restart webserver - docker,redhat
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Debian | Enable misp apache config
  ansible.builtin.file:
    src: "{{ apache_sitedir }}/misp.conf"
    dest: /etc/apache2/sites-enabled/misp.conf
    mode: '0644'
    state: link
  notify:
    - Restart webserver
    - Restart webserver - docker,debian
    - Restart webserver - docker,redhat
  when: ansible_os_family == 'Debian'
