---

## No gpg signature: https://github.com/composer/composer/issues/38
## https://composer.github.io/pubkeys.html
## https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md
- name: Download Composer installer.
  get_url:
    url: "{{ item.u }}"
    dest: "{{ item.d }}"
    mode: "{{ item.m }}"
  with_items:
    - { u: 'https://getcomposer.org/installer', d: '/tmp/composer-installer.php', m: '0755' }
    - { u: 'https://composer.github.io/installer.sig', d: '/tmp/installer.sig', m: '0400' }

- name: get installer checksum
  stat:
    path: /tmp/composer-installer.php
    checksum_algorithm: sha384
  register: installer
- name: get signature hash
  command: cat /tmp/installer.sig
  register: installersig
  changed_when: false
  ignore_errors: true

- block:
    - debug: var=installer.stat.checksum
    - debug: var=installersig.stdout
    - name: check composer signature
      fail: msg="FATAL! composer signature not matching."
  when: installer.stat.checksum != installersig.stdout

- name: install composer
  command: "php -q /tmp/composer-installer.php --install-dir=/usr/local/bin --filename=composer"
  args:
    creates: /usr/local/bin/composer

- name: install PHP dependencies via composer (kamisama/cake-resque, Vendor)
  composer:
    command: install
    working_dir: "{{ misp_rootdir }}/app"
  register: pkg_result
  until: pkg_result is success
  become: yes
  become_user: "{{ www_user }}"
