---

- name: Debian | MISP dependencies install
  ansible.builtin.apt:
    name: "{{ misp_pkg_list + webserver }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  async: 3600
  poll: 300
  register: pkg_result
  until: pkg_result is success
