---


- name: Debian PHP7.4 | Add ondrej/php repository from PPA
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php

- name: Debian PHP7.4 | Ensure php is present
  ansible.builtin.apt:
    name: "{{ misp_pkg_list + webserver }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  async: 3600
  poll: 300
  register: pkg_result
  until: pkg_result is success
