---
# https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.rhel7.txt#L368

- name: Ensure lief dependencies are present
  ansible.builtin.package:
    name: cmake
    state: present

- name: Install lief with pip
  ansible.builtin.pip:
    name: lief
    state: present
    version: "{{ misp_lief_version | default(omit) }}"
    virtualenv: "{{ misp_virtualenv }}"
    virtualenv_python: "{{ python3_bin }}"
  when: >
    ansible_os_family == 'Debian' or
    (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7)
  register: pkg_result
  until: pkg_result is success
  become: yes
  become_user: "{{ www_user }}"

- name: Ensure LIEF is working
  ansible.builtin.command: "python -c 'import lief'"
  environment:
    PATH: "{{ misp_virtualenv }}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  changed_when: false
