---

- name: Flush handlers as we need service up for API call
  ansible.builtin.meta: flush_handlers

## FIXME! not idempotent, no way to list feeds with their status
- name: Enable feeds
  ansible.builtin.uri:
    url: "{{ misp_local_base_url | default(misp_base_url) }}/feeds/enable/{{ item }}"
    method: POST
    headers:
      Authorization: "{{ userkey }}"
      Accept: application/json
      Content-Type: application/json
    validate_certs: False
  with_items: "{{ misp_enable_feeds }}"
  register: enableresults

# - debug: var=enableresults

- name: Fetch from feeds
  ansible.builtin.uri:
    url: "{{ misp_local_base_url | default(misp_base_url) }}/feeds/fetchFromFeed/{{ item }}"
    method: GET
    headers:
      Authorization: "{{ userkey }}"
      Accept: application/json
      Content-Type: application/json
    validate_certs: False
  with_items: "{{ misp_fetch_feeds }}"
  register: fetchresults

- name: Disable feeds
  ansible.builtin.uri:
    url: "{{ misp_local_base_url | default(misp_base_url) }}/feeds/disable/{{ item }}"
    method: POST
    headers:
      Authorization: "{{ userkey }}"
      Accept: application/json
      Content-Type: application/json
    validate_certs: False
  with_items: "{{ misp_disable_feeds }}"
  register: disableresults

# - debug: var=disableresults
