---

## FIXME! how to do it once only!
## Note: more a reset as next login, will ask to change password...
- name: Check if admin pass already set
  stat: path="{{ misp_rootdir }}/.admin_pass_set"
  register: ap
- name: set admin password
  command: "{{ misp_rootdir }}/app/Console/cake Password \"{{ misp_web_user }}\" \"{{ misp_web_pass }}\""
  become: yes
  become_user: "{{ www_user }}"
  when: not ap.stat.exists
- name: Admin pass set marker
  file:
    dest: "{{ misp_rootdir }}/.admin_pass_set"
    mode: '0600'
    state: touch
  when: not ap.stat.exists

# - block:
#     - name: set extra users
#       command: "{{ misp_rootdir }}/app/Console/cake Password {{ item.u }} \"{{ item.p }}\""
#       with_items: "{{ misp_webusers_list }}"
#   when: misp_webusers_list is defined and misp_webusers_list

- include: misp-key-file.yml

- name: set local variables in PyMISP/examples/keys.py
  lineinfile:
    dest: "{{ misp_rootdir }}/PyMISP/examples/keys.py"
    regexp: "{{ item.re }}"
    line: "{{ item.l }}"
    create: yes
    mode: '0640'
    group: "{{ www_user }}"
  with_items:
    - { re: "^misp_url = .*", l: "misp_url = \"{{ misp_pymisp_base_url | default(misp_base_url) }}\"" }
    - { re: "^misp_key = .*", l: "misp_key = \"{{ userkey }}\"" }
    - { re: '^misp_verifycert = .*', l: "misp_verifycert = {{ misp_pymisp_verifycert }}" }
  no_log: "{{ misp_no_log }}"

- name: flush handlers as we need service up for API call
  meta: flush_handlers

- name: wait for MISP port to be opened
  wait_for:
    host: "{{ misp_base_ip }}"
    port: "{{ misp_base_port }}"
    timeout: 300

- name: ensure PyMISP API working
  command: "{{ misp_virtualenv }}/bin/python ./last.py -l 10"
  become: yes
  become_user: "{{ www_user }}"
  args:
    chdir: "{{ misp_rootdir }}/PyMISP/examples"
  environment:
    debug: True
    PYTHONPATH: /usr/local/lib/python3.6/site-packages
  register: test
  changed_when: false
  ignore_errors: true

- name: list current users
  command: "{{ misp_virtualenv }}/bin/python ./users_list.py"
  become: yes
  become_user: "{{ www_user }}"
  args:
    chdir: "{{ misp_rootdir }}/PyMISP/examples"
  environment:
    PYTHONPATH: /usr/local/lib/python3.6/site-packages
  register: listusers
  changed_when: false

- block:
    - include: "misp-add-user.yml user={{ item }} list={{ listusers }}"
      with_items: "{{ misp_webusers_list }}"
  when: misp_webusers_list is defined and misp_webusers_list != []
