---

- name: yum | remi yum-utils
  yum: name=yum-utils state=present update_cache=yes
  register: pkg_result
  until: pkg_result is success

## for php-redis
- import_tasks: redhat-remi.yml
  when: ansible_os_family == "RedHat"

- name: RedHat8+ | Enable PowerTools repo
  ini_file:
    dest: /etc/yum.repos.d/CentOS-Stream-PowerTools.repo
    section: powertools
    option: "{{ item.o }}"
    value: "{{ item.v }}"
    mode: '0644'
  with_items:
    - { o: enabled, v: '1' }
    - { o: baseurl, v: 'http://mirror.centos.org/$contentdir/$releasever/PowerTools/$basearch/os/' }
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8

- name: Check available repositories
  command: dnf repolist
  changed_when: false
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8

- name: yum | MISP dependencies install
  yum:
    name: "{{ misp_pkg_list + webserver }}"
    state: present
    update_cache: yes
  async: 3600
  poll: 300
  register: pkg_result
  until: pkg_result is success

- block:
    - name: set php-fpm to use socket file
      replace:
        dest: /etc/php-fpm.d/www.conf
        regexp: "{{ item.re }}"
        replace: "{{ item.rep }}"
        mode: '0644'
        backup: yes
      with_items:
        - { re: '^listen = .*$', rep: 'listen = /var/run/php-fpm/php-fpm.sock' }
        - { re: '^;listen.owner = nobody', rep: 'listen.owner = {{ fpm_user }}' }
        - { re: '^;listen.group = nobody', rep: 'listen.group = {{ fpm_user }}' }
        - { re: '^listen.owner = .*$', rep: 'listen.owner = {{ fpm_user }}' }
        - { re: '^listen.group = .*$', rep: 'listen.group = {{ fpm_user }}' }
      notify:
        - restart php-fpm

    - name: ensure socket dir exists
      file: dest=/var/run/php-fpm state=directory owner=nobody group=nobody mode=0755

    - name: set php-fpm user/group to nginx
      replace:
        dest: /etc/php-fpm.d/www.conf
        regexp: "{{ item.re }}"
        replace: "{{ item.rep }}"
        mode: '0644'
        backup: yes
      with_items:
        - { re: '^user = .*$', rep: 'user = nginx' }
        - { re: '^group = .*$', rep: 'group = nginx' }
      notify:
        - restart php-fpm
  when: misp_webserver is defined and misp_webserver == 'nginx'

- name: redhat | ensure python36 site-packages directory exists
  file:
    dest: /usr/local/lib/python3.6/site-packages
    owner: root
    mode: '0755'
    state: directory

# https://github.com/ansible/ansible/issues/16612
- block:
    - name: Debug | ansible_selinux var
      debug: var=ansible_selinux
    - name: RedHat7- | Ensure selinux dependencies are present
      package:
        name:
          - libselinux-python
          - libsemanage-python
          - policycoreutils-python
        state: present
      register: pkg_result
      until: pkg_result is success
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int < 8
    - name: RedHat8+ | Ensure selinux dependencies are present
      package:
        name:
          - python3-libselinux
          - python3-libsemanage
          - python3-policycoreutils
        state: present
      register: pkg_result
      until: pkg_result is success
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8
    - name: re-collect facts
      action: setup
    - name: Debug | ansible_selinux var
      debug: var=ansible_selinux
  when: ansible_os_family == "RedHat"
- block:
    - name: RedHat | Allow proxy to network connect in selinux
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes

    - name: RedHat | Allow httpd to listen to unusual ports
      seport:
        ports: "{{ misp_base_port }}"
        proto: tcp
        setype: http_port_t
        state: present
      when: misp_base_port != 80 and misp_base_port != 443
  when: ansible_os_family == "RedHat" and ansible_selinux.status is defined and ansible_selinux.status != 'disabled'
