---

- name: get the package facts
  package_facts:
    manager: "auto"

- name: show packages
  debug: var=ansible_facts.packages

- name: Import Remi rpm repository keys
  rpm_key:
    key: "{{ item }}"
    state: present
  with_items:
    - https://rpms.remirepo.net/RPM-GPG-KEY-remi
    - https://rpms.remirepo.net/RPM-GPG-KEY-remi2017
    - https://rpms.remirepo.net/RPM-GPG-KEY-remi2018
  register: pkg_result
  until: pkg_result is success

- name: RedHat6 | Install Remi repo
  yum: name=http://rpms.remirepo.net/enterprise/remi-release-6.rpm
       state=present
  when: ansible_distribution_major_version == "6" and 'remi-release' not in ansible_facts.packages
  register: pkg_result
  until: pkg_result is success
- name: RedHat7 | Install Remi repo
  yum: name=http://rpms.remirepo.net/enterprise/remi-release-7.rpm
       state=present
  when: ansible_distribution_major_version == "7" and 'remi-release' not in ansible_facts.packages
  register: pkg_result
  until: pkg_result is success
- name: RedHat8 | Install Remi repo
  yum: name=http://rpms.remirepo.net/enterprise/remi-release-8.rpm
       state=present
  when: ansible_distribution_major_version == "8" and 'remi-release' not in ansible_facts.packages
  register: pkg_result
  until: pkg_result is success

- name: check if remi-php repo is enabled
  command: "grep '^enabled=' /etc/yum.repos.d/remi-php{{ php_remi_version }}.repo"
  register: remistate
  changed_when: false
  when: ansible_distribution_major_version|int < 8

# https://github.com/ansible/ansible-modules-extras/issues/2384
- name: enable remi repository for php
  command: "yum-config-manager --enable remi-php{{ php_remi_version }}"
  # yum_repository:
  #   name: remi-php56
  #   enable: yes
  when:
    - ansible_distribution_major_version|int < 8
    - remistate.stdout is defined
    - not ('enabled=1' in remistate.stdout)

# https://github.com/ansible/ansible-modules-extras/issues/2384
- name: RHEL8 | enable remi repository for php
  ini_file:
    dest: /etc/yum.repos.d/remi.repo
    section: remi
    option: enabled
    value: 1
  when: ansible_distribution_major_version|int >= 8
