---
# https://redis.io/topics/security
# https://www.digitalocean.com/community/tutorials/how-to-secure-your-redis-installation-on-ubuntu-18-04

- name: Redis | configure network binding
  ansible.builtin.lineinfile:
    dest: "{{ redis_conf }}"
    regexp: '^bind .*'
    line: "bind {{ misp_redis_bind }}"
    mode: '0644'
    backup: yes

- name: Redis | require password
  ansible.builtin.lineinfile:
    dest: "{{ redis_conf }}"
    regexp: '^requirepass .*'
    line: "requirepass {{ misp_redis_password }}"
    mode: '0644'
    backup: yes
  when: misp_redis_password is defined and misp_redis_password

- name: Redis | rename dangerous commands
  ansible.builtin.lineinfile:
    dest: "{{ redis_conf }}"
    regexp: "{{ item.re }}"
    line: "{{ item.l }}"
    mode: '0644'
  with_items: "{{ misp_redis_securecommands }}"
  when: misp_redis_securecommands is defined and misp_redis_securecommands != []
