---

- name: review misp error.log
  command: "tail {{ misp_rootdir }}/app/tmp/logs/error.log"
  changed_when: false
  failed_when: false

- include: travis.yml

- name: install testing tools
  package:
    name: "{{ misp_testing_pkg }}"
    state: present
  register: pkg_result
  until: pkg_result is success

- name: replace misp.local hostname
  replace:
    dest: "{{ misp_rootdir }}/tests/curl_tests.sh"
    regexp: 'http:\/\/misp.local'
    replace: "{{ misp_base_url }}"
    mode: '0755'
    backup: yes
- name: check tool version for debugging
  command: "{{ item }}"
  with_items:
    - php --version
    - composer --version
  changed_when: false
  become: yes
  become_user: "{{ www_user }}"
- name: pip dependencies for testing
  pip:
    name: ['coveralls', 'codecov', 'nose', 'requests-mock', 'poetry']
    virtualenv: "{{ misp_virtualenv }}"
    virtualenv_python: "{{ python3_bin }}"
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  register: pkg_result
  until: pkg_result is success
  become: yes
  become_user: "{{ www_user }}"

- name: ensure test user in group of web server
  user: "user={{ misp_testing_user }} groups={{ www_user }} append=yes"
  become: yes

- name: check home permissions
  file: dest={{ item }} mode=0755 state=directory
  with_items:
    - "{{ misp_testing_user_home }}/build"
    - "{{ misp_testing_user_home }}"
    - /home

# Get authkey
- name: check world-writeable permissions
  file: "dest={{ item }} mode=0777 owner={{ misp_testing_user }} recurse=yes"
  with_items:
    - "{{ misp_rootdir }}/build"
    - "{{ misp_rootdir }}/tests"

# - name: use MISP travis bootstrap
#   copy:
#     src: "{{ misp_rootdir }}/travis/bootstrap.php"
#     dest: "{{ misp_rootdir }}/app/Config/bootstrap.php"
#     backup: yes
#     force: yes

- include: misp-key-file.yml

- name: MISP tree permissions
  ## break .gnupg if applied to whole tree
  # file: "dest={{ misp_rootdir }} owner={{ www_user }} mode=755 recurse=yes"
  file: "dest={{ misp_rootdir }} owner={{ www_user }} mode=0755"
  become: yes
- name: MISP tree permissions
  file: "dest={{ item }} owner={{ www_user }} mode=0755"
  ## Note: recurse is only valid if directory and can't select them from fileglob
  # with_fileglob:
  #   - "{{ misp_rootdir }}/*"
  ## Not doing root files, build/tests/PyMISP addressed in their own tasks, INSTALL/travis ignored
  with_items:
    - "{{ misp_rootdir }}/app"
    - "{{ misp_rootdir }}/format"
    - "{{ misp_rootdir }}/tools"
  become: yes
- name: PyMISP world-writeable permissions
  file:
    dest: "{{ misp_rootdir }}/PyMISP"
    mode: '0777'
    owner: "{{ misp_testing_user }}"
    recurse: yes
  become: yes
## FIXME! for some reason .coverage still own by root during serverspec test
- name: PyMISP .coverage permissions
  file:
    dest: "{{ misp_rootdir }}/PyMISP/.coverage"
    mode: '0777'
    owner: "{{ misp_testing_user }}"
    state: touch
- name: PyMISP pymisp.egg-info permissions
  file:
    dest: "{{ misp_rootdir }}/PyMISP/pymisp.egg-info"
    mode: '0777'
    owner: "{{ misp_testing_user }}"
    state: directory
    recurse: yes

- name: Debug | misp_base_url var
  debug: var=misp_base_url
- name: Debug | userInit var
  debug: var=userInit
- name: set local variables in PyMISP/tests/keys.py
  lineinfile:
    dest: "{{ misp_rootdir }}/PyMISP/tests/keys.py"
    line: "{{ item }}"
    mode: '0600'
    owner: "{{ misp_testing_user }}"
    create: yes
  with_items:
    - "url = \"{{ misp_pymisp_base_url | default(misp_base_url) }}\""
    - "key = \"{{ userkey }}\""
  no_log: "{{ misp_no_log }}"
- name: symlink key file in examples/events
  file:
    src: "{{ misp_rootdir }}/PyMISP/tests/keys.py"
    dest: "{{ misp_rootdir }}/PyMISP/examples/events/keys.py"
    mode: '0600'
    owner: "{{ misp_testing_user }}"
    state: link
    force: yes
- name: symlink key file in PyMISP
  file:
    src: "{{ misp_rootdir }}/PyMISP/tests/keys.py"
    dest: "{{ misp_rootdir }}/PyMISP/keys.py"
    mode: '0600'
    owner: "{{ misp_testing_user }}"
    state: link
    force: yes

- name: allow self-signed certificates in curl_tests.sh
  replace:
    dest: "{{ misp_rootdir }}/tests/curl_tests.sh"
    regexp: '^curl -([iH].)'
    replace: 'curl -k -\1'
    mode: '0755'
    backup: yes

- name: review misp error.log 2
  command: "tail {{ misp_rootdir }}/app/tmp/logs/error.log"
  changed_when: false
  failed_when: false
